version: "3.7"

services:
  proxy:
    image: traefik:2.10
    container_name: traefik
    restart: always
    networks:
      mynet:
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=webs"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.webs.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=tiago.ferreira@ifsc.edu.br"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    volumes:
      - "vol-rproxy:/etc/traefik/acme"
      - "/var/run/docker.sock:/var/run/docker.sock"
  db:
    image: linuxserver/mariadb:10.6.13
    container_name: librebooking-db
    restart: always
    depends_on:
      - proxy
    networks:
      - mynet
    volumes:
      - vol-db:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=librebooking
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/db_root_pwd
      - MYSQL_USER=lb_user
      - FILE__MYSQL_PASSWORD=/run/secrets/db_user_pwd
    secrets:
      - db_root_pwd
      - db_user_pwd
  app:
    image: librebooking/librebooking:2.8.6.1
    container_name: librebooking
    restart: always
    depends_on:
      - db
    networks:
      - mynet
    volumes:
      - vol-app:/config
    environment: 
      - LB_DB_NAME=librebooking
      - LB_INSTALL_PWD_FILE=/run/secrets/lb_install_pwd
      - LB_DB_USER=lb_user
      - LB_DB_USER_PWD_FILE=/run/secrets/lb_user_pwd
      - LB_DB_HOST=db
      - LB_ENV=production
      - LB_LOG_FOLDER=/var/log/librebooking
      - LB_LOG_LEVEL=error
      - LB_LOG_SQL=false
      - TZ=America/Sao_Paulo
    secrets:
      - lb_install_pwd
      - lb_user_pwd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librebooking.rule=Host(`librebooking.teste`)"
      - "traefik.http.routers.librebooking.tls.certresolver=myresolver"
      - "traefik.http.services.librebooking.loadbalancer.server.port=80"

volumes:
  vol-rproxy:
    name: traefik_certs
  vol-db:
    name: librebooking_data
  vol-app:
    name: librebooking_conf

networks:
  mynet:

secrets:
  db_root_pwd:
    file: ./db_root_pwd.txt
  db_user_pwd:
    file: ./db_user_pwd.txt
  lb_user_pwd:
    file: ./db_user_pwd.txt
  lb_install_pwd:
    file: ./lb_install_pwd.txt